apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-auth-postgres-pvc
  namespace: hospital
  labels:
    app: ms-auth-postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
