apiVersion: v1
kind: Service
metadata:
  name: ms-waitlist-postgres-svc
  namespace: hospital
spec:
  selector:
    app: ms-waitlist-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
