apiVersion: v1
kind: Service
metadata:
  name: ms-waitlist-svc
  namespace: hospital
  labels:
    app: ms-waitlist
spec:
  selector:
    app: ms-waitlist
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP
