apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: hospital
  labels:
    app: bff
spec:
  selector:
    app: bff
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8090
  # ClusterIP — solo accesible internamente desde el api-gateway
  # El punto de entrada externo ahora es api-gateway (:8091)
  type: ClusterIP
