apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user
  namespace: hospital
  labels:
    app: ms-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-user
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ms-user
    spec:
      containers:
        - name: ms-user
          image: ms-user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: ms-user-config
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: ms-user-db-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ms-user-db-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ms-user-db-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          startupProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 0
            periodSeconds: 15
            failureThreshold: 5
