apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-user-postgres
  namespace: hospital
  labels:
    app: ms-user-postgres
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-user-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms-user-postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: msuser_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ms-user-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-user-db-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "msuser_user", "-d", "msuser_db"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "msuser_user", "-d", "msuser_db"]
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: ms-user-postgres-pvc
