# =============================================================================
# SECRETS — ms-user
# IMPORTANTE: Reemplaza los valores antes de aplicar.
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: ms-user-db-secret
  namespace: hospital
  labels:
    app: ms-user
    tier: database
type: Opaque
stringData:
  POSTGRES_USER:     "msuser_user"
  POSTGRES_PASSWORD: "CHANGE_ME_DB_PASSWORD"
  DB_URL:            "jdbc:postgresql://ms-user-postgres-svc:5432/msuser_db"
